### ISSUE TITLE
Newsletter link causing 404 problems

### ISSUE THREAD

**Issue by glenpike** [CoderDojo/coderdojo.com#72] opened 2020-09-16 09:27 UTC
Amy sent out a newsletter with a link to 'https://coderdojo.com/ways-to-run/', but some people are having issues when following it.

Some people are using the link, but it is directing them to something like this: https://coderdojo.com/ways-to-run/?mc_cid=00fa411f0a&mc_eid=5ced5a2ba5

Which then causes problems with redirection from Zen to CoderDojo's Netlify/Vue site.

Hunch is that the query string maybe something user-specific, but this should be ignored when checking if the URL should be redirected, etc.

**Comment by patch0** [comment] 2020-09-16 10:26
Duplicate of #71 :)

**Closed by patch0** 2020-09-16 10:26 UTC
